apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: diogo96/query-service
          env:
            - name: POSTS_SERVICE_URL
              value: "http://posts-service-srv:4000"
            - name: COMMENTS_SERVICE_URL
              value: "http://comments-service-srv:4001"
            - name: QUERY_SERVICE_URL
              value: "http://query-service-srv:4002"
            - name: MODERATION_SERVICE_URL
              value: "http://moderation-service-srv:4003"
            - name: EVENT_BUS_URL
              value: "http://event-bus-srv:4005"
---
  apiVersion: v1
  kind: Service
  metadata:
    name: query-service-srv
  spec:
    selector:
      app: query-service
    ports:
      - name: query-service
        protocol: TCP
        port: 4002
        targetPort: 4002
---
  apiVersion: v1
  kind: Service
  metadata:
    name: query-service-node-port
  spec:
    type: NodePort
    selector:
      app: query-service
    ports: 
      - name: query-service
        protocol: TCP
        port: 4002
        targetPort: 4002